# Generated by Django 2.1.11 on 2019-10-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('eimage', models.ImageField(upload_to='')),
                ('salary', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('contactno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
