# Generated by Django 2.1.11 on 2019-10-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20191011_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eimage',
        ),
    ]
