# Generated by Django 2.1.11 on 2019-10-10 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_remove_employee_eimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            field=models.CharField(default=datetime.datetime(2019, 10, 10, 22, 12, 43, 559385, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
