# Generated by Django 3.1.7 on 2021-03-10 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20201229_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='branch',
            new_name='branch',
        ),
    ]
